name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch: [x64, x86]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10 for ${{ matrix.arch }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: ${{ matrix.arch }}

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller

    - name: Build executable with PyInstaller for ${{ matrix.arch }}
      run: |
        pyinstaller --onefile --noconsole --icon=favicon.ico --name "PPSUC-OneClickLogin-${{ matrix.arch }}" PPSUC-OneClickLogin.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-executables-${{ matrix.arch }}
        path: dist/*

  release:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Artifacts for x64
      uses: actions/download-artifact@v3
      with:
        name: windows-executables-x64
        path: ./dist-x64

    - name: Download Artifacts for x86
      uses: actions/download-artifact@v3
      with:
        name: windows-executables-x86
        path: ./dist-x86

    - name: Create Release
      id: create_release
      uses: ghcr.io/softprops/action-gh-release@v1
      with:
        files: ./dist-x64/*, ./dist-x86/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
